django/app/urls.py
from django.urls import URLPattern, path
from django.conf.urls import url
from .views import Test, Signin , Turfs



urlpatterns = [
    path('', Test.as_view(), name="base"),
    path('login/', Signin.as_view(), name="sign-in"),
    

    path('turfs/', Turfs.as_view(), name="turfs"),
]

django/myturf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings  
from django.conf.urls.static import static  


urlpatterns = [
    path('', include('User.urls')),
    path('shop/', include('e_commerce.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', include('app.urls')),
    path('', include('User.urls')),
    path('',include('dashboard.urls')),
    path('',include('accounts.urls')),

]


if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

django/User/forms.py
from pickle import NONE
from time import time
from django import forms
from django.forms import ModelForm
# from requests import request
# from django.contrib.auth import authenticate
from .models import *
from datetime import datetime
from pytz import timezone
from dashboard.models import CategoriesModel


class RequestForm(ModelForm):
    category = forms.ModelChoiceField(queryset=CategoriesModel.objects.all(),widget=forms.HiddenInput())
    date = forms.DateField(widget=forms.HiddenInput())
    start_time = forms.TimeField(widget=forms.HiddenInput())
    end_time = forms.TimeField(widget=forms.HiddenInput())
    username= forms.ModelChoiceField(queryset=UserModel.objects.all(),widget=forms.HiddenInput())
    locality=forms.CharField(widget=forms.HiddenInput())
    status=forms.CharField(widget=forms.HiddenInput())
    # match_id= forms.ModelMultipleChoiceField(queryset=RequestModel.objects.all())
    match_id=forms.IntegerField(widget=forms.HiddenInput())
    phoneno=forms.IntegerField(widget=forms.HiddenInput())
    class Meta():
        model = RequestModel    
        # exclude = '__all__'
        fields =('category','date','start_time','end_time','username','locality','status','phoneno')
    

    def __init__(self,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(RequestForm, self).__init__(*args, **kwargs)
        # self.fields['category'].disabled = True



    def clean(self):
        print("---------------Inside RequestForm's Clean Method-------------------")
        self.cleaned_data = super().clean()
        print(self.cleaned_data.get('match_id'))
        print(self.cleaned_data.get('category'))
        match=MatchModel.objects.get(id=int(self.cleaned_data.get('match_id')))
        user=UserModel.objects.get(id=self.request.user.pk)
        print(self.cleaned_data.get('username'))
        print(match.category)
        if self.cleaned_data.get('category') != match.category:
            self._errors['category']=self.error_class(['Do not change the category'])
            print(" category  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('date')!=match.date:
            self._errors['date']=self.error_class(['Do not change the date'])
            print("date  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('start_time')!=match.start_time.astimezone(timezone('Asia/Kolkata')).time():
            self._errors['start_time']=self.error_class(['Do not change the start_time'])
            print("start_time   erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('end_time')!=match.end_time.astimezone(timezone('Asia/Kolkata')).time():
            self._errors['end_time']=self.error_class(['Do not change the end_time'])
            print("end_time  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        if self.cleaned_data.get('locality')!=match.locality:
            self._errors['locality']=self.error_class(['Do not change the locality'])
            print("locality  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")   
        if self.cleaned_data.get('username')!=user.id:
            self._errors['username']=self.error_class(['Do not change the user'])
            print("username  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")  
        # self.cleaned_data['username']=user
        # print("phone number in form",self.cleaned_data.get('phoneno'),"its type is",type(self.cleaned_data.get('phoneno')))
        # print("phone number in session",self.request.user.phone,"its type is",type(self.request.user.phone))
        if self.cleaned_data.get('phoneno')!=int(self.request.user.phone):
            self._errors['phoneno']=self.error_class(['Do not change the phone number'])
            print("phone number  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr") 
        if self.cleaned_data.get('status')!="Pending":
            self._errors['status']=self.error_class(['Do not change the status'])
            print("status  erorrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr")
        else:
            print("no erorrrrrrrrrrrrrrrrrrrrrrr")
        return self.cleaned_data

# choices=OPTIONS


class creatematchForm(ModelForm):

    options =[
        ("Cricket", "Cricket"),
        ("Football", "Football"),
        ("Baseball", "Baseball"),
        ("Badminton", "Badminton"),
        ("Tennis", "Tennis"),
        ("Volleyball","Volleyball"),
        ("Basketball","Basketball")
    ]
    # cat=CategoriesModel.objects.all().values_list('category')
    # print(cat)
    # print("------------------------hardcoded options--------------------------",options)
    # options1 =[
    #     # for c in cat:
    #     #     (c,c)
    # ] 
    # print(options1)

    category= forms.ModelChoiceField(queryset=CategoriesModel.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time_f = forms.TimeField(required=False,widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    end_time_f = forms.TimeField(required=False, widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    start_time = forms.DateTimeField(widget=forms.HiddenInput())
    end_time = forms.DateTimeField(widget=forms.HiddenInput())
    slots = forms.IntegerField()#nos = number of slots           
    creator= forms.CharField(widget=forms.HiddenInput())
    locality=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    city=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    # status=forms.CharField(widget=forms.HiddenInput())
    slot_available=forms.IntegerField(widget=forms.HiddenInput())
    # cron=forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = MatchModel
        fields = 'category','date','start_time_f','end_time_f','start_time','end_time','slots','city','locality','creator'
    
    def __init__(self,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(creatematchForm, self).__init__(*args, **kwargs)

    def clean(self):
        print("hasgfsdyfgsdhjfdg")
        self.cleaned_data = super().clean()
        slots=self.cleaned_data.get('slots')
        creator=self.cleaned_data.get('creator')
        status=self.cleaned_data.get('status')
        city=self.cleaned_data.get('city')
        if city :
            list=city.split(", ")
            if len(list) ==3:
                check_city=CitiesModel.objects.filter(name=list[0],subcountry=list[1],country=list[2])
                if len(check_city) == 0:
                     self._errors['city']=self.error_class(['Please Select a City from the provided list'])
            else:
                self._errors['city']=self.error_class(['Please Select a City from the provided list'])
        start_time_f=self.cleaned_data.get('start_time_f')
        end_time_f=self.cleaned_data.get('end_time_f')
        print(slots)
        if slots != None and slots >= 2:
            self.cleaned_data['slot_available']=slots-1
        else :
            self._errors['slots']=self.error_class(['No of slots can not be less than 2'])
        self.cleaned_data['creator']=self.request.user.username
        if creator !=  self.request.user.username:
            self._errors['creator']=self.error_class([''])
        # if status != "Upcoming":
        #     self._errors['status']=self.error_class([''])
        self.cleaned_data['status']="Upcoming"
        if   start_time_f != None and end_time_f !=None :
                if start_time_f >= end_time_f:
                    self._errors['start_time_f']=self.error_class(['Start time can not be more than end time'])
        elif  start_time_f == None:
                self._errors['start_time_f']=self.error_class(['Start time must be time type'])
        elif  end_time_f == None:
                self._errors['end_time_f']=self.error_class(['End time must be time type'])
        print("khsfdagjfdghsuj",slots,self.cleaned_data['slot_available'])
        return self.cleaned_data



class updatematchform(ModelForm):

    options =[
        ("Cricket", "Cricket"),
        ("Football", "Football"),
        ("Baseball", "Baseball"),
        ("Badminton", "Badminton"),
        ("Tennis", "Tennis"),
        ("Volleyball","Volleyball"),
        ("Basketball","Basketball")
    ]

    match_id = forms.ModelChoiceField(queryset=MatchModel.objects.all(),widget=forms.HiddenInput())
    category= forms.ModelChoiceField(queryset=CategoriesModel.objects.all())
    date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    start_time_f = forms.TimeField(required=False,widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    end_time_f = forms.TimeField(required=False, widget=forms.TimeInput(attrs={'type': 'time','step' : '1'}))
    start_time = forms.DateTimeField(widget=forms.HiddenInput())
    end_time = forms.DateTimeField(widget=forms.HiddenInput())
    slots = forms.IntegerField()#nos = number of slots           
    creator= forms.CharField(widget=forms.HiddenInput())
    locality=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    city=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    # status=forms.CharField(widget=forms.HiddenInput())
    slot_available=forms.IntegerField(widget=forms.HiddenInput())
    # cron=forms.IntegerField(widget=forms.HiddenInput())
    class Meta:
        model = MatchModel
        fields = 'category','date','start_time_f','end_time_f','start_time','end_time','slots','city','locality','creator'
    
    def __init__(self,*args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(updatematchform, self).__init__(*args, **kwargs)

    def clean(self):
        print("hasgfsdyfgsdhjfdg")
        self.cleaned_data = super().clean()
        slots=self.cleaned_data.get('slots')
        creator=self.cleaned_data.get('creator')
        status=self.cleaned_data.get('status')
        start_time_f=self.cleaned_data.get('start_time_f')
        end_time_f=self.cleaned_data.get('end_time_f')

django/templates/Matches/all-matches.html
{% extends 'layouts/base.html' %}

{% block content %}
<!-- {% if messages %}
  {% for message in messages %}
      <p class="d-none" id="messagetag">{{message.tags}}</p>
      <p class="d-none " id="messagecontent">{{message}}</p>
  {% endfor %}
    {% endif %} -->
    <div class="ecomerce-top-bar card p-3" {% if is_requestform %} style="display: none ;" {% else %}
    style="display: flex ;" {% endif %}>
        <div class="row justify-content-between">
            <div class="col-4">
                <span class="item-name"> 
                    <form method="POST"  class="d-flex">
                        {% csrf_token %}
                        <div class="pt-2">
                           <p>Current Location  : </p>  
                        </div>
                     <div>
                        <input type="text"  value="{{request.user.current_location}}" required="True" name="location" id="id_city" hx-post="{%url 'search-city' feildname="location" %}" hx-target='#results' hx-trigger="keyup changed delay:500ms"  class="form-control"  placeholder="Select a City ..." >
                    </div>
                    <button type="submit" name="location_change" class="btn-primary rounded-2 mb-2 mt-2 mx-2">Change</button>
                </form>
                <div id="results" class="suggestion"></div>
                </span>
            </div>
            <div class="col-4"></div>
            <div class="col-4  ecomerce-top-bar-btns justify-content-end mx-auto">
                <form method="POST">
                    {% csrf_token %}
                    <input type="text" name="search" hx-post="{%url 'search-matches' %}" hx-target='#result-matches' hx-trigger="keyup changed delay:500ms"  class="form-control"  placeholder="Select a  Username, Date or Category ..." >
                </form>
            </div>
        </div>
    </div>
<div class="row bg-soft-light d-flex justify-content-around"  {% if is_requestform %} style="display: none ;" {% else %}
style="display: block ;" {% endif %} id="result-matches">
{% include 'Matches/matches.html' %}
</div>
<div class="row mt-5" id="RequestForm" {% if is_requestform  %} style="display: flex ;" {% else %}
style="display: none ;" {% endif %}>
<div class="col-lg-6 mx-auto">
    <div class=" card ">
        <div class="card-body">
            <form method="POST">
                <div class="modal-header">
                    <h5 class="modal-title mx-auto">Send join request
                    </h5> 
                </div>
                <div class="modal-body p-4">
                    {% csrf_token %}
              


                    <div class="row">
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="{{RequestForm.category.id_for_label}}" class="form-label">Category</label>
                               
                                <p class="form-control" style="    background-color: #e9ecef;
                                opacity: 1;">{{data.category}}</p>
                            </div>
                            <span class="text-error text-danger">{{ RequestForm.category.errors }}</span>
                        </div>

                        <div class="col-lg-12">
                          <div class="form-group">
                              <label for="start" class="form-label">Date</label>
                                                        <p class="form-control" style="    background-color: #e9ecef;
                              opacity: 1;">{{data.date|date:"Y-m-d"}}</p>
                          </div>
                          <span class="text-error text-danger">{{ RequestForm.date.errors }}</span>
                      </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="start" class="form-label">Start Time</label>
                                <p class="form-control" style="    background-color: #e9ecef;
                                opacity: 1;">{{data.start_time}}</p>
                            </div>
                            <span class="text-error text-danger">{{ RequestForm.start_time.errors }}</span>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label for="end" class="form-label">End Time</label>
                               
                                <p class="form-control" style="    background-color: #e9ecef;
                                opacity: 1;">{{data.end_time}}</p>
                            </div>
                            <span class="text-error text-danger">{{ RequestForm.end_time.errors }}</span>
                        </div>

                        <div class="col-lg-12">
                          <div class="form-group">
                              <label for="end" class="form-label">Location</label>
                             
                              <p class="form-control" style="    background-color: #e9ecef;
                              opacity: 1;">{{data.locality}}</p>
                          </div>
                          <span class="text-error text-danger">{{ RequestForm.locality.errors }}</span>
                      </div>
                    </div>





                   

                   
                   
                   

                </div>
                <div class="modal-footer">
                  
                     <!-- <a href="{% url 'turf_schedule' %}" class="btn btn-secondary">Close</a>
                 
                    <button type="button"  class="btn btn-secondary"
                        onclick="closeRequestForm()">Close</button> -->
                    
                    
                    <button type="submit" class="btn btn-success"> Send requests</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="col-lg-2 mx-5">
    <div class="card">
        <div class="card-header">
            <h3 class="text-center">The Team</h3>
        </div>
        <div class="card-body bg-light">
            {% for joined in joined%}
            {% if match.creator == joined.username%}
            <div class="card row d-flex flex-row bg-danger text-white">
            <div class="col-4"><img src="/static/assets/images/avatars/01.png" alt="User-Profile" class="theme-color-default-img img-fluid rounded-pill avatar-50"></div>
            <div class="col-8 my-auto">{{joined.username}}</div>
        </div>
            {%else%}
            <div class="card row d-flex flex-row">
            <div class="col-4 "><img src="/static/assets/images/avatars/01.png" alt="User-Profile" class="theme-color-default-img img-fluid rounded-pill avatar-50"></div>
            <div class="col-8 my-auto ">{{joined.username}}</div></div>
            {%endif%}
            
            {%endfor%}
        </div>
    </div>
</div>

</div>
<!-- <rssapp-wall id="tblR6sxbIzZJcii6"></rssapp-wall><script src="https://widget.rss.app/v1/wall.js" type="text/javascript" async></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
<script>
    document.getElementById('matches-li').classList.add('active')
    // $(document).ready(function(){
    //     let tag=$('#messagetag').html()
    //     let message = $('#messagecontent').html()
    //       if( tag == 'error'){
    //         toastr.error(message);
    //         $('#creatematch').trigger('reset');
    //       }
    //       if( tag == 'success' ){
    //         toastr.success(message);
    //         $('#creatematch').trigger('reset');
    //       }
    //   });
//     let dropdowns = document.querySelectorAll('.dropdown-toggle')
// dropdowns.forEach((dd)=>{
//     dd.addEventListener('click', function (e) {
//         var el = this.nextElementSibling
//         el.style.display = el.style.display==='block'?'none':'block'
//     })
// })

</script>
<style>
/* .sub-menu:hover .games-menu {
    display: block;
  } */
  /* .dropdown-submenu {
  position: relative;
}

.dropdown-submenu a::after {
  transform: rotate(-90deg);
  position: absolute;
  right: 6px;
  top: .8em;
}

.dropdown-submenu .dropdown-menu {
  top: 0;
  left: 100%;
  margin-left: .1rem;
  margin-right: .1rem;
} */
  </style>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.1/jquery.min.js" integrity="sha512-aVKKRRi/Q/YV+4mjoKBsE4x3H+BkegoM/em46NNlCqNTmUYADjBbeNefNxYV7giUp0VxICtqdrbqU7iVaeZNXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script> -->
<script>
    
    function useSuggestion(e) {
    if(e.target.innerText!="No search results.Enter a valid name atleast 3 characters in length"){
        
        console.log(e.target.innerText)
        id_city.value = e.target.innerText;
        id_city.focus();
        suggestions.innerHTML = '';
        let city=id_city.value;
        // suggestions.classList.remove('has-suggestions');
    }
	
}
const suggestions = document.querySelector('.suggestion');
suggestions.addEventListener('click', useSuggestion);
document.addEventListener('click', () =>suggestions.innerHTML = '' );

</script>
{% include 'style/location_style.html' %}
{% endblock content %}

django/templates/Matches/cities-list.html
{% if results %}

{% csrf_token %}
<ul class="list-group col-xs-12">
{% for result in results %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
        {{ result.name }}, {{result.subcountry}}, {{result.country}}
    </li>
{% endfor %}
</ul>
{% else %}
<p>No search results.Enter a valid name atleast 3 characters in length</p>
{% endif %}

django/templates/Matches/create-matches.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}



<section class="ecommerce-addstock-section container-fluid m-3">
    <!-- ecommerce topbar -->
    <!-- {% if messages %}
    {% for message in messages %}
        <p class="d-none" id="messagetag">{{message.tags}}</p>
        <p class="d-none " id="messagecontent">{{message}}</p>
    {% endfor %}
      {% endif %} -->
    <div class="ecomerce-top-bar ">
        <div class="row">
            <h1 class=" mt-5" style="text-align:center">CREATE YOUR OWN MATCH</h1>
        </div>
    </div>
    <!-- ecommerce main section -->
    <div class="ecom-addstock my-3">
        <div class="card col-md-6 mx-auto mt-5 p-5">
            <div class="">
                <form method="POST" id="creatematch">
                    {% csrf_token %}
                    <!-- {{form.errors}} -->


                    {% for addForm in form.visible_fields %}


                    {% if addForm.label != "Category" and addForm.label != "City" %}
                    <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                        {% render_field addForm class="form-control" placeholder="Place Holder" min="1"%}
                        {% if addForm.type != "hidden"%}
                        {% if addForm.label == "Start time f" %}
                        <label>Start Time</label>
                        {% elif addForm.label == "End time f" %}
                        <label>End Time</label>
                        {% else %}
                        <label>{{addForm.label}}</label>
                        {% endif %}
                        {%endif%}
                        <!-- <p>{{addform.type}} helllll</p> -->
                        <span class="text-danger">{{addForm.errors}}</span>
                    </div>
                    {% endif %}
                    <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                    {%if  addForm.label == "City" %}
                    {% render_field addForm hx-post='/search-city/city' hx-target='#results' hx-trigger="keyup changed delay:100ms"  class="form-control"  placeholder="Select Your City ..." %}
                    <label>Search your {{addForm.label}}</label>
                    <span class="text-danger">{{addForm.errors}}</span>
                    <div id="results" class="suggestion"></div>
                    </div>
                    {%endif%}
                    {%if addForm.label == "Category" %}
                    {% render_field form.category  class="form-control  mb-4"%}

                    {% endif %}
                   
                    {% endfor %}
                    {%for dontForm in form.hidden_fields%}
                    {% render_field dontForm.as_hidden %}
                    {%endfor%}
                    
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>

<script>document.getElementById('create-matches-li').classList.add('active')</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var today = new Date().toISOString().split('T')[0];
        $("#id_date").attr('min', today);
        $('#creatematch').trigger('reset');
    });
</script>
<script>
function useSuggestion(e) {
    if(e.target.innerText!="No search results.Enter a valid name atleast 3 characters in length"){
        
        console.log(e.target.innerText)
        id_city.value = e.target.innerText;
        id_city.focus();
        suggestions.innerHTML = '';
        // suggestions.classList.remove('has-suggestions');
    }
	
}
const suggestions = document.querySelector('.suggestion');
suggestions.addEventListener('click', useSuggestion);
document.addEventListener('click', () =>suggestions.innerHTML = '' );

</script>
{% include 'style/location_style.html' %}

{% endblock content %}

django/templates/Matches/edit-matches.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}



<section class="ecommerce-addstock-section container-fluid m-3">
    <!-- ecommerce topbar -->
    <!-- {% if messages %}
    {% for message in messages %}
        <p class="d-none" id="messagetag">{{message.tags}}</p>
        <p class="d-none " id="messagecontent">{{message}}</p>
    {% endfor %}
      {% endif %} -->
    <div class="ecomerce-top-bar ">
        <div class="row">
            <h1 class=" mt-5" style="text-align:center">EDIT YOUR OWN MATCH</h1>
        </div>
    </div>
    <!-- ecommerce main section -->
    <div class="ecom-addstock my-3">
        <div class="card col-md-6 mx-auto mt-5 p-5">
            <div class="">
                <form method="POST" id="creatematch">
                    {% csrf_token %}
                    <!-- {{form.errors}} -->


                    {% for addForm in form.visible_fields %}


                    {% if addForm.label != "Category" and addForm.label != "City" %}
                    <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                        {% render_field addForm class="form-control" placeholder="Place Holder" min="1"%}
                        {% if addForm.type != "hidden"%}
                        {% if addForm.label == "Start time f" %}
                        <label>Start Time</label>
                        {% elif addForm.label == "End time f" %}
                        <label>End Time</label>
                        {% else %}
                        <label>{{addForm.label}}</label>
                        {% endif %}
                        {%endif%}
                        <!-- <p>{{addform.type}} helllll</p> -->
                        <span class="text-danger">{{addForm.errors}}</span>
                    </div>
                    {% endif %}
                    <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                    {%if  addForm.label == "City" %}
                    {% render_field addForm hx-post='/search-city/city' hx-target='#results' hx-trigger="keyup changed delay:500ms"  class="form-control"  placeholder="Select Your City ..." %}
                    <label>Search your {{addForm.label}}</label>
                    <span class="text-danger">{{addForm.errors}}</span>
                    <div id="results" class="suggestion"></div>
                    </div>
                    {%endif%}
                    {%if addForm.label == "Category" %}
                    {% render_field form.category  class="form-control  mb-4"%}

                    {% endif %}
                   
                    {% endfor %}
                    {%for dontForm in form.hidden_fields%}
                    {% render_field dontForm.as_hidden %}
                    {%endfor%}
                    
                    <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>

<script>document.getElementById('my-matches-li').classList.add('active')</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var today = new Date().toISOString().split('T')[0];
        $("#id_date").attr('min', today);
        $('#creatematch').trigger('reset');
    });
</script>
<script>
function useSuggestion(e) {
    if(e.target.innerText!="No search results.Enter a valid name atleast 3 characters in length"){
        
        console.log(e.target.innerText)
        id_city.value = e.target.innerText;
        id_city.focus();
        suggestions.innerHTML = '';
        // suggestions.classList.remove('has-suggestions');
    }
	
}
const suggestions = document.querySelector('.suggestion');
suggestions.addEventListener('click', useSuggestion);
document.addEventListener('click', () =>suggestions.innerHTML = '' );
</script>
{% include 'style/location_style.html' %}

{% endblock content %}