django/app/urls.py
from django.urls import URLPattern, path
from django.conf.urls import url
from .views import Test, Signin , Turfs



urlpatterns = [
    path('', Test.as_view(), name="base"),
    path('login/', Signin.as_view(), name="sign-in"),
    

    path('turfs/', Turfs.as_view(), name="turfs"),
]

django/myturf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.conf import settings  
from django.conf.urls.static import static  


urlpatterns = [
    path('', include('User.urls')),
    path('shop/', include('e_commerce.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('home/', include('app.urls')),
    path('', include('User.urls')),
    path('',include('dashboard.urls')),
    path('',include('accounts.urls')),

]


if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)  

django/User/models.py
from email.policy import default
from unicodedata import category
from django.db import models
from unittest.util import _MAX_LENGTH
from datetime import datetime,timedelta
from dashboard.models import CategoriesModel
from accounts.models import UserModel
from django.contrib.postgres.fields import ArrayField
# Create your models here.


   
class MatchModel(models.Model):
    category = models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    date= models.DateField(blank=True)
    start_time= models.DateTimeField(max_length=30,default=datetime.now(),blank=True)
    end_time= models.DateTimeField(max_length=30,default=datetime.now(),blank=True)
    locality = models.CharField(max_length=50,null=True,blank=False)
    city=models.CharField(max_length=100,null=True,blank=False)
    creator = models.CharField(max_length=30,null=True,blank=False)
    status = models.CharField(default="Upcoming",max_length=30,null=False,blank=False)
    slots =models.IntegerField(default=2,null=False,blank=False)
    slot_available =models.IntegerField(default = 1,null=False,blank=False)
    cron =models.IntegerField(default = 1,null=True,blank=False)



class RequestModel(models.Model):
    match_id = models.ForeignKey(MatchModel, on_delete=models.CASCADE)
    category=models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    username=models.ForeignKey(UserModel, on_delete=models.CASCADE)
    phoneno=models.CharField(max_length=16,default=7414414141)
    status=models.CharField(default="Pending",max_length=30,null=False,blank=False)
    date= models.DateField(blank=True)
    start_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    end_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    locality = models.CharField(max_length=50,null=True,blank=False)

    
class TournamentModel(models.Model):
    category = models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    # team_name =  models.ForeignKey('User.CreateTeamModel', on_delete=models.CASCADE)
    team_name = models.CharField(max_length=30,null=True,blank=False)
    start_date= models.DateField(blank=True)
    end_date= models.DateField(blank=True) 
    start_time= models.DateTimeField(max_length=30,default=datetime.now(),blank=True)
    end_time= models.DateTimeField(max_length=30,default=datetime.now(),blank=True)
    locality = models.CharField(max_length=30,null=True,blank=False)
    creator = models.CharField(max_length=30,null=True,blank=False)
    status = models.CharField(default="Upcoming",max_length=30,null=False,blank=False)
    teams =models.IntegerField(default=1,null=False,blank=False)
    team_space_available =models.IntegerField(default = 1,null=False,blank=False)

    # start_time= models.DateTimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    # end_time= models.DateTimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
class TournamentRequestModel(models.Model):
    tournament_id = models.ForeignKey(TournamentModel, on_delete=models.CASCADE)
    category=models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    # team_name =  models.ForeignKey("CreateTeamModel", on_delete=models.CASCADE)
    team_name = models.CharField(max_length=30,null=True,blank=False)
    username=models.CharField(max_length=30,null=False,blank=False)
    phoneno=models.CharField(max_length=16,default=7414414141)
    status=models.CharField(default="Pending",max_length=30,null=False,blank=False)
    start_date= models.DateField(blank=True)
    end_date= models.DateField(blank=True) 
    start_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    end_time= models.TimeField(default=datetime.now().strftime('%H:%M:%S'),blank=True)
    locality = models.CharField(max_length=30,null=True,blank=False)

class CreateTeamModel(models.Model):
    team_name = models.CharField(max_length=30,blank=False,null=False)
    # category=models.ForeignKey(CategoriesModel, on_delete=models.CASCADE)
    # members=models.IntegerField()
    # # tournament_id=models.ForeignKey(TournamentModel, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.team_name)



class TurfCommentsModel(models.Model):
    turf = models.ForeignKey(UserModel, on_delete=models.CASCADE , related_name='turf')
    commenter = models.ForeignKey(UserModel, on_delete=models.CASCADE , related_name='commenter')
    comment = models.CharField(max_length=1000,null=False,blank=False)
    likes_count = models.IntegerField(default=0, null=False)
    date = models.DateTimeField(max_length=30,default=datetime.now())
    liked_users = ArrayField(models.CharField(max_length=512, null=False) , null=False, default=list) 


class CitiesModel(models.Model):
    name=models.CharField(max_length=100,null=True,blank=False)
    country=models.CharField(max_length=100,null=True,blank=False)
    subcountry=models.CharField(max_length=100,null=True,blank=False)
    geonameid=models.IntegerField(default=1,null=True,blank=False)

django/templates/Tournaments/create-team.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}



<section class="ecommerce-addstock-section container-fluid ">

    <div class="ecomerce-top-bar card p-3">
        <div class="row">
            <div class="col-4">
                <span class="item-name" style="font-size: 1.4rem;"><h4>CREATE YOUR TEAM</h4></span>
            </div>
        </div>
    </div>

    <div class="ecom-addstock ">
        <div class="card col-md-6 mx-auto mt-0 p-5">
            <div class="">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {% for addForm in form %}
                    
                    <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-5">
                        {% render_field addForm class="form-control" placeholder="Place Holder"  %}
                        {% if addForm.label != "category" %}
                            <label >{{addForm.label}}</label>
                        {% else %}
                        {% endif %}
                    </div>
                    <span class="text-danger">{{addForm.errors}}</span>
                    {% endfor %}
                    
                    <button class="btn btn-primary" type="submit">Submit</button>

                </form>
            </div>
        </div>
    </div>
</section>






<script>
    document.getElementById('create-team-li').classList.add('active')
</script>












{% endblock content %}

django/templates/Tournaments/create-tournament.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}



<section class="ecommerce-addstock-section container-fluid m-3"  >
    <!-- ecommerce topbar -->
    <!-- {% if messages %}
    {% for message in messages %}
        <p class="d-none" id="messagetag">{{message.tags}}</p>
        <p class="d-none " id="messagecontent">{{message}}</p>
    {% endfor %}
      {% endif %} -->
    <div class="ecomerce-top-bar ">
        <div class="row">
                <h1 class=" mt-5"style="text-align:center">CREATE YOUR OWN TOURNAMENT</h1>
        </div>
    </div>
    <!-- ecommerce main section -->
    <div class="ecom-addstock my-3">
        <div class="bg-white col-md-6 mx-auto mt-5 p-5">
            <div class="">
                <form method="POST" id="create-tournament-li">
                    {% csrf_token %}
                    <!-- {{form.errors}} -->
                    
        
                    {% for addForm in form.visible_fields %}
                                
                    
                        {% if addForm.label != "Category" %}
                        <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                            {% render_field addForm class="form-control" placeholder="Place Holder" min="1"%}
                            {% if addForm.type != "hidden"%}
                            {% if addForm.label == "Start time f" %}
                            <label >Start Time</label>
                            {% elif addForm.label == "End time f" %}
                            <label >End Time</label>
                            {% else %}
                            <label >{{addForm.label}}</label>
                            {% endif %}
                            {%endif%}
                            <span class="text-danger">{{addForm.errors}}</span>
                        </div>
                        {% else %}
                            {% render_field form.category class="form-select form-select-lg mb-4" aria-label=".form-select-lg example" name="category" id="category" %}
                           
                            {% endif %}
                      
                          
        
                    {% endfor %}
                    {%for dontForm in form.hidden_fields%}
                    {% render_field dontForm.as_hidden %}
                    {%endfor%}
                        <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>

<script>document.getElementById('create-tournament-li').classList.add('active')</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
  <script type="text/javascript">
    //  $(document).ready(function(){
    //     let tag=$('#messagetag').html()
    //     let message = $('#messagecontent').html()
    //       if( tag == 'error'){
    //         toastr.error(message);
    //         $('#creatematch').trigger('reset');
    //       }
    //       if( tag == 'success' ){
    //         toastr.success(message);
    //         $('#creatematch').trigger('reset');
    //       }
    //   });
      $(document).ready(function() {
      var today = new Date().toISOString().split('T')[0];
      $("#id_start_date").attr('min', today);
      $("#id_end_date").attr('min', today);

      $('#createtournament').trigger('reset');
      });
  </script>
<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&key=AIzaSyAPaN2ndJcLY_fajOnaFwpkBVfIwSEfvgw"></script>
<script>
google.maps.event.addDomListener(window, 'load', function () 
{   
    
    var options = {
        // types: ['(cities)'],
        componentRestrictions: {country: 'in'}
    };
	var places = new google.maps.places.Autocomplete(document.getElementById('id_locality'),options);
    google.maps.event.addListener(places, 'place_changed', function () 
	{
		console.log(places.getPlace());
		var getaddress 	  = places.getPlace();				//alert(getaddress.address_components[0].long_name);
		var whole_address = getaddress.address_components;  //alert(whole_address + 'whole_address');   
		$('#id_locality').val('');
});
});
</script> -->
<style>
.bd-example{
      display:flex;
      flex-direction:column;
      align-items:center;
      width: 75rem;
      height: 43rem;
}
</style>



{% endblock content %}







































<!-- <section class="ecommerce-addstock-section container-fluid my-3"  >
 
    {% if messages %}
    {% for message in messages %}
        <p class="d-none" id="messagetag">{{message.tags}}</p>
        <p class="d-none " id="messagecontent">{{message}}</p>
    {% endfor %}
      {% endif %}
    <div class="ecomerce-top-bar ">
        <div class="row">
                <h1 class=" mt-5"style="text-align:center">CREATE YOUR OWN TOURNAMENT</h1>
        </div>
    </div>
    
    <div class="ecom-addstock my-3">
        <div class="bg-white col-md-6 mx-auto mt-5 p-5">
            <div class="">
                <form method="POST" id="create-tournament-li">
                    {% csrf_token %}
                    
        
                    {% for addForm in form.visible_fields %}
                                
                       
                        {% if addForm.label != "Category" %}
                        <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                            {% render_field addForm class="form-control" placeholder="Place Holder" min="1"%}
                            {% if addForm.type != "hidden"%}
                            <label >{{addForm.label}}</label>
                            {%endif%}
                            <p>{{addForm.type}}</p>
                        </div>
                        {% else %}
                            {% render_field form.category class="form-select form-select-lg mb-4" aria-label=".form-select-lg example" name="category" id="category" %}
                        {% endif %}
                        <span class="text-danger">{{addForm.errors}}</span>
                        
        
                    {% endfor %}
                    {%for dontForm in form.hidden_fields%}
                    {% render_field dontForm %}
                    {%endfor%}
                        <button class="btn btn-primary" type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
</section>

<script>document.getElementById('create-tournament-li').classList.add('active')</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
  <script type="text/javascript">
     $(document).ready(function(){
        let tag=$('#messagetag').html()
        let message = $('#messagecontent').html()
          if( tag == 'error'){
            toastr.error(message);
            $('#createtournament').trigger('reset');
          }
          if( tag == 'success' ){
            toastr.success(message);
            $('#createtournament').trigger('reset');
          }
      });
      $(document).ready(function() {
      var today = new Date().toISOString().split('T')[0];
      $("#id_start_date").attr('min', today);
      $("#id_end_date").attr('min', today);

      $('#createtournament').trigger('reset');
      });
  </script>


<style>
.bd-example{
      display:flex;
      flex-direction:column;
      align-items:center;
      width: 75rem;
      height: 43rem;
      
      

}
</style> -->

django/templates/Tournaments/edit-tournaments.html
{% extends 'layouts/base.html' %}
{% load widget_tweaks %}
{% block content %}
<section class="ecommerce-addstock-section container-fluid my-3" >
  <!-- ecommerce topbar -->
  {% if messages %}
  {% for message in messages %}
      <p class="d-none" id="messagetag">{{message.tags}}</p>
      <p class="d-none " id="messagecontent">{{message}}</p>
  {% endfor %}
    {% endif %}
  <div class="ecomerce-top-bar ">
      <div class="row">
              <h1 class=" mt-5"style="text-align:center">EDIT YOUR TOURNAMENT</h1>
      </div>
  </div>
  <!-- ecommerce main section -->
  <div class="ecom-addstock my-3">
      <div class="bg-white col-md-6 mx-auto mt-5 p-5">
          <div class="">
              <form method="POST">
                  {% csrf_token %}
                  
                  {% for addForm in form.visible_fields %}
                              
                     
                  {% if addForm.label != "Category" %}
                  <div class="form-floating custom-form-floating custom-form-floating-sm form-group mb-4">
                      {% render_field addForm class="form-control" placeholder="Place Holder" min="2" %}
                      {% if addform.type != "hidden"%}
                        {% if addForm.label == "Start time f" %}
                        <label >Start Time</label>
                        {% elif addForm.label == "End time f" %}
                        <label >End Time</label>
                        {% else %}
                        <label >{{addForm.label}}</label>
                        {% endif %}
                        {%endif%}
                  </div>
                  {% else %}
                      {% render_field form.category class="form-select form-select-lg mb-4" aria-label=".form-select-lg example" name="category" id="category" %}
                  {% endif %}
                  <span class="text-danger">{{addForm.errors}}</span>
                  
  
              {% endfor %}
              {%for dontForm in form.hidden_fields%}
              {% render_field dontForm %}
              {%endfor%}
                      <button class="btn btn-primary" type="submit">Submit</button>
              </form>
          </div>
      </div>
  </div>
</section>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet"/>
      
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
  <script type="text/javascript">
     $(document).ready(function(){
        let tag=$('#messagetag').html()
        let message = $('#messagecontent').html()
          if( tag == 'error'){
            toastr.error(message);
          }
          if( tag == 'success' ){
            toastr.success(message);
          }
      });
      $(document).ready(function() {
      var today = new Date().toISOString().split('T')[0];
      $("#id_start_date").attr('min', today);
      $("#id_end_date").attr('min', today);

      });

  </script>
{%endblock content%}

django/templates/Tournaments/my-tournament.html
{% extends 'layouts/base.html' %}
{% block content %}

<div class="container-fluid">
    {% if tournaments%}
    <div class="row bg-light justify-content-around">
        {% if tournaments %}
<div class="row bg-light justify-content-around container-fluid">
        {% for r in tournaments %}
       
    <div class="column col-md-4">
        <div class="card p-2 m-4">
            <img src="/media/{{r.category.image}}" class="card-img-top flex" alt="Product 1" style="height:14rem;">
            <div class="card-body p-1 ">
            <h2 class="card-text p-1 text-dark ">{{r.category}}</h2>
            <p class="card-text text-dark">Tournament Day : <span class="text-secondary">{{r.start_date|date:"Y-m-d"}}</span></p>
            <p class="card-text text-dark">Time : <span class="text-secondary">{{r.start_time|time:"H:i:s"}}</span> to  <span class="text-secondary">{{r.end_time|time:"H:i:s"}}</span></p>
            <p class="card-text text-dark">Available Slots:{{r.team_space_available}}/{{r.team_space_available}}</p>
            <p class="card-text text-dark">Locality:{{r.locality}}</p>
            {% if r.creator == request.user.username %}
            <a href="edit/{{r.id}} "  class="btn btn-primary">
                EDIT
            </a>
            {%else%}
            <p class="card-text ">Organized By:{{r.creator}}</p>
            {%endif%}
            </div>
        </div>
    </div>
    {%endfor%}
    
    </div>
 {% else %}

 <div class="row bg-light justify-content-center">
    <div class="column col-md-4 justify-content-md-around">
        <div class="card text-white bg-soft-info m-5" > 
          <div class="card-body">   
            <h3 class="mt-3 text-center">There aren't any matches you have created or joined</h3>
            <p class="mt-3 text-center">
              Interested in creating your own tournament<a class="nav-link " href="{% url 'my-tournament' %}" id="create-tournament-li">Click here</a>
            </p>
          </div>
          </div>
    </div>
    </div>
    {%endif%}
</div>

{%endif%}
<script>
    document.getElementById('my-tournaments-li').classList.add('active')
  
</script>




{% endblock content %}

django/templates/Tournaments/requested-tournaments.html
{% extends 'layouts/base.html' %}
{% block content %}


<div class="container-fluid">
  {%if tournaments%}
<div class="container-fluid">
  <div class="row  bg-soft-light">
    {% for t in tournaments%}
      <div class="column col-md-4">
          <div class="card p-2 m-5">
              <img src="/media/{{t.category.image}}" class="card-img-top flex" alt="Product 1" style="height:14rem;">
                <div class="card-body">
                <h2 class="card-text p-1 text-dark ">{{t.category}}</h2>
                <p class="card-text text-dark">Tournament Day : <span class="text-secondary">{{t.start_date|date:"Y-m-d"}}</span></p>
                <p class="card-text text-dark">Time : <span class="text-secondary">{{t.start_time|time:"H:i:s"}}</span> to  <span class="text-secondary">{{t.end_time|time:"H:i:s"}}</span></p>
                <p class="card-text text-dark">Available Slots:{{t.team_space_available}}/{{t.team_space_available}}</p>
                <p class="card-text text-dark">Locality:{{t.locality}}</p>
                <a  class="btn btn-primary" href="cancel/{{t.id}}">
                  Cancel
                </a>
              </div>
            </div>
        </div>
     {%endfor%}
  </div>
</div>
 {%else%}
 <div class="row bg-light justify-content-center">
  <div class="column col-md-4 justify-content-md-around">
      <div class="card text-white bg-soft-info m-5" > 
        <div class="card-body">   
          <h3 class="mt-3 text-center">There aren't any tournaments you have requested to join</h3>
          <p class="mt-3 text-center">
            Interested in creating your own tournaments<a class="nav-link " href="{% url 'create-tournament' %}" id="create-tournament-li">Click here</a>
          </p>
        </div>
        </div>
  </div>
  </div>
  {%endif%}
</div>
<script>
    document.getElementById('requested-tournament-li').classList.add('active')
</script>
{% endblock content %}

django/templates/Tournaments/requests.html
{% extends 'layouts/base.html' %}
{% block content %}

        <div class="position-relative iq-banner">
        <!-- Nav Header Component Start -->
            <div class="iq-navbar-header" style="height: 215px;">
                <div class="container-fluid iq-container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="flex-wrap d-flex justify-content-between align-items-center">
                                <div>
                                    <h1>Manage Requests</h1>
                                    <p></p>
                                </div>
                                <div>
                                    <a href="" class="btn btn-link btn-soft-light">
                                        <svg width="20" viewBox="0 0 24 24" fill="none"
                                            xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M11.8251 15.2171H12.1748C14.0987 15.2171 15.731 13.985 16.3054 12.2764C16.3887 12.0276 16.1979 11.7713 15.9334 11.7713H14.8562C14.5133 11.7713 14.2362 11.4977 14.2362 11.16C14.2362 10.8213 14.5133 10.5467 14.8562 10.5467H15.9005C16.2463 10.5467 16.5263 10.2703 16.5263 9.92875C16.5263 9.58722 16.2463 9.31075 15.9005 9.31075H14.8562C14.5133 9.31075 14.2362 9.03619 14.2362 8.69849C14.2362 8.35984 14.5133 8.08528 14.8562 8.08528H15.9005C16.2463 8.08528 16.5263 7.8088 16.5263 7.46728C16.5263 7.12575 16.2463 6.84928 15.9005 6.84928H14.8562C14.5133 6.84928 14.2362 6.57472 14.2362 6.23606C14.2362 5.89837 14.5133 5.62381 14.8562 5.62381H15.9886C16.2483 5.62381 16.4343 5.3789 16.3645 5.13113C15.8501 3.32401 14.1694 2 12.1748 2H11.8251C9.42172 2 7.47363 3.92287 7.47363 6.29729V10.9198C7.47363 13.2933 9.42172 15.2171 11.8251 15.2171Z"
                                                fill="currentColor"></path>
                                            <path opacity="0.4"
                                                d="M19.5313 9.82568C18.9966 9.82568 18.5626 10.2533 18.5626 10.7823C18.5626 14.3554 15.6186 17.2627 12.0005 17.2627C8.38136 17.2627 5.43743 14.3554 5.43743 10.7823C5.43743 10.2533 5.00345 9.82568 4.46872 9.82568C3.93398 9.82568 3.5 10.2533 3.5 10.7823C3.5 15.0873 6.79945 18.6413 11.0318 19.1186V21.0434C11.0318 21.5715 11.4648 22.0001 12.0005 22.0001C12.5352 22.0001 12.9692 21.5715 12.9692 21.0434V19.1186C17.2006 18.6413 20.5 15.0873 20.5 10.7823C20.5 10.2533 20.066 9.82568 19.5313 9.82568Z"
                                                fill="currentColor"></path>
                                        </svg>
                                        
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="iq-header-img">
                    <img src="/static/assets/images/dashboard/top-header.png" alt="header"
                        class="theme-color-default-img img-fluid w-100 h-100 animated-scaleX">
                    <img src="/static/assets/images/dashboard/top-header1.png" alt="header"
                        class="theme-color-purple-img img-fluid w-100 h-100 animated-scaleX">
                    <img src="/static/assets/images/dashboard/top-header2.png" alt="header"
                        class="theme-color-blue-img img-fluid w-100 h-100 animated-scaleX">
                    <img src="/static/assets/images/dashboard/top-header3.png" alt="header"
                        class="theme-color-green-img img-fluid w-100 h-100 animated-scaleX">
                    <img src="/static/assets/images/dashboard/top-header4.png" alt="header"
                        class="theme-color-yellow-img img-fluid w-100 h-100 animated-scaleX">
                    <img src="/static/assets/images/dashboard/top-header5.png" alt="header"
                        class="theme-color-pink-img img-fluid w-100 h-100 animated-scaleX">
                </div>
            </div> <!-- Nav Header Component End -->
            <!--Nav End-->
        </div>
        <div class="conatiner-fluid content-inner mt-n5 py-0">

<div class="row ">
  <div class="col-12">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
                            <div class="header-title">
                                <h4 class="card-title">Pending Request</h4>
                            </div>
                        </div>
                        <div class="card-body">
                          <form action="" method="POST">
                            {% csrf_token %}
        <div class="d-flex justify-content-end">
          <div class="btn-group   mb-5">
            <button type="button" class="btn btn-primary">Action</button>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split"
              data-bs-toggle="dropdown" aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu">
              <div class="d-flex flex-column gap-2">
                <li class="mx-auto w-75"> <button class="btn-soft-success btn w-100" type="submit"
                  name="Accept">Accept</button></li>
                <li class="mx-auto w-75"> <button class="btn-soft-danger btn w-100" type="submit"
                  name="Reject"> Reject </button>
                </li>
            </div>
            </ul>
          </div>
        </div>  

        <div class="table-responsive">
            <table id="datatable" class="table table-striped" data-toggle="data-table">
              <thead class=" text-primary">
                <th>
                  <label><input type="checkbox" name="sample" class="selectall" /></label>
                </th>
                <th>
                  #
                </th>
                <th>
                  Category
                </th>
                <th>
                  Username
                </th>
                <th>
                  Phone No
                </th>
                <th>
                  Start_Date
                </th>
                <th>
                  End_Date
                </th>
                <th>
                  Start Time
                </th>
                <th>
                  End Time
                </th>
                <th>
                  Location
                </th>
              </thead>

              <tbody>
                {%for data in requests%}
                <tr>
                  <td><input type="checkbox" name="selected[]" id="checks[]" value="{{data.id}}"></td>
                  <td>{{forloop.counter0|add:1}}</td>
                  <td>{{data.category}}</td>
                  <td>{{data.username }}</td>
                  <td>{{data.phoneno}}</td>
                  <td>{{data.start_date|date:"Y-m-d"}}</td>
                  <td>{{data.end_date|date:"Y-m-d"}}</td>
                  <td>{{data.start_time|time:"h:i:s"}}</td>
                  <td>{{data.end_time|time:"h:i:s"}}</td>
                  <td>
                    {{data.locality}}
                  </td>

                </tr>

                {% endfor %}
              </tbody>
            </table>

          </div>
          
        </form>
        </div>
    </div>
  </div>
</div>
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
<script>
  document.getElementById('tournament-request-li').classList.add('active')
  $('.selectall').click(function () {
    if ($(this).is(':checked')) {
      $('input:checkbox').attr('checked', true);
    } else {
      $('input:checkbox').attr('checked', false);
    }
  });
</script>
{% endblock content %}